name: FoliaPlaceholders
version: 1.0.0
main: com.example.foliaplaceholders.Plugin
authors:
  - leir4iks
description: PlaceholderAPI expansion for Folia region TPS and MSPT placeholders.
api-version: "1.21"
server:
  dependencies:
    - name: PlaceholderAPI
      required: true
      load: AFTER
      join-classpath: true
